### PR TITLE
ci: switch to testing on node 14 and 16

### LINKED ISSUE #1027: run CI on node16
now node12 is out of support we want to support node 14 as the default, and node 16 as future in CI

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #1027

### CODE REVIEW

**Comment by willdurand** [comment]
The node 16 error seems to be caused by a change in `npm unlink`. It apparently requires an argument now.

**Review by willdurand — APPROVED** [review]
Looks good, thanks.

We'll need to release a new version and given we're switching to a new node version to build the package, I'd bump the major version (I've done that for some libs in the past). I will take care of that.

⚠️ please squash your commits when merging this patch, do not introduce a merge commit. Thanks!

**Comment by willdurand** [comment]
ugh, for some reasons I thought this PR was merged and I released `4.0.0`... without this PR :| That's why I just merged this PR and released `4.0.1`. Sorry about that!

**Comment by eviljeff** [comment]
> ⚠️ please squash your commits when merging this patch, do not introduce a merge commit. Thanks!

Looks like the other merge types are disabled on this repo anyway - only squash and merge is available.

**Comment by willdurand** [comment]
> Looks like the other merge types are disabled on this repo anyway - only squash and merge is available.

Ha, that's cool and good to know, thanks. We should do that for all repos :D

**Pull request merged**
