### PR TITLE
change milleseconds to milliseconds.

### PR DESCRIPTION
**Pull request by mv15**
I noticed a typo in this file.

### CODE REVIEW

**Comment by willdurand** [comment]
thanks!

**Comment by caitmuenster** [comment]
Thanks for the update, @mv15! ✨ Your contributions have been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you.

**Comment by mv15** [comment]
@caitmuenster Yeah, sure. I am new to open source. I'd be happy to learn new things.

**Comment by caitmuenster** [comment]
Awesome, and welcome! If you want to set up an account and send me the URL of your profile, I can vouch for you. 

If you're interested in getting more involved, please feel welcome to check out [additional ways](https://www.mozilla.org/contribute/) you can contribute to Mozilla. :)

**Pull request merged**
