### PR TITLE
Fix request() call

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/sign-addon/issues/321

### CODE REVIEW

**Comment by kumar303** [comment]
Ugh, thanks for the fix @willdurand. Does the avoidance of `TypeError` still need test coverage or did your changes to the mock reproduce the failure?

**Comment by willdurand** [comment]
> Does the avoidance of `TypeError` still need test coverage or did your changes to the mock reproduce the failure?

We never handled the promise error, so I guess we'd need to do that (with a `.catch()` at the end of the promise chain) and a few test cases.

**Comment by kumar303** [comment]
Yeah, throwing errors is fine. I was just wondering, do we have a test that exercises the path that had originally thrown `TypeError`?

**Comment by willdurand** [comment]
I don't think we have a test case for that, but I am not sure we can reproduce the `TypeError` with the current code.

**Pull request merged**
