### PR TITLE
Made progress bar optional in Client

### LINKED ISSUE #710: Make progress bar optional
See https://github.com/mozilla/web-ext/issues/2154 for context

The progress bar, initialized at https://github.com/mozilla/sign-addon/blob/af0fe2d2d6f2ac8321f7db0145db3b5495b8c66b/src/amo-client.js#L183-L188 (and implemented at https://github.com/mozilla/sign-addon/blob/af0fe2d2d6f2ac8321f7db0145db3b5495b8c66b/src/PseudoProgress.js) should be optional.

The `Client` is initialized by the `signAddon` function at https://github.com/mozilla/sign-addon/blob/af0fe2d2d6f2ac8321f7db0145db3b5495b8c66b/src/index.js#L95-L105
which is called by `web-ext sign` at https://github.com/mozilla/web-ext/blob/9c53dd4e4afc4be7111cc009a15dff8dea22f09d/src/cmd/sign.js#L115-L127

### PR DESCRIPTION
**Pull request by vyshnavrajs2019**
Fixes #710 
@willdurand _A please review

### CODE REVIEW

**Comment by vyshnavrajs2019** [comment]
@willdurand _A

**Review by willdurand — COMMENTED** [review]
Thanks, that looks like a good start to me!

I think we should cover these changes with some test cases.

**Comment by willdurand** [comment]
Ok so I updated this patch to add some tests and expose the new config parameter to the main `signAddon()` function. Progress bar is completely disabled when this param is set to `true`, which, I think, is what we want, especially reading https://github.com/mozilla/web-ext/issues/2154

**Review by Rob--W — APPROVED** [review]

**Comment by willdurand** [comment]
thanks for your contribution @vyshnavrajs2019! /cc @caitmuenster

**Comment by caitmuenster** [comment]
Yes, thanks so much, @vyshnavrajs2019! 🎉 Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition).

Hope to see you around the project in the future!

**Pull request merged**
