### PR TITLE
Ignore .vscode files

### PR DESCRIPTION
**Pull request by kumar303**

### CODE REVIEW

**Comment by willdurand** [comment]
That is why configuring a global gitignore is a better solution: https://help.github.com/en/github/using-git/ignoring-files#create-a-global-gitignore. Otherwise, you'll have to patch all the TS repos you'll touch..

**Comment by kumar303** [comment]
Well, I was thinking there might be some cases where I wouldn't want to ignore a `.vscode` file in a project, like, if it had some effect that all team members would need to take advantage of. I am not aware of any such effect so I'll just add a global ignore until I think of one. Thanks for the feedback.

**Comment by kumar303** [comment]
I try to only put things like `*.pyc` in my global ignore, things that are unambiguously ephemeral artifacts. Otherwise, it creates surprises for contributors.

**Comment by willdurand** [comment]
Yeah, mine is a list of some very annoying things I collected over time: https://github.com/willdurand/dotfiles/blob/master/git/gitignore_global

**Pull request closed without merging**
